/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Twisted Metal 2)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: jal at 0x8011E4F4; NOP-ing that call gives 'Drive Through Walls' */
#define PSX_FN_CollisionWallResponse 0x800E3800u
#define func_800E3800 CollisionWallResponse  /* alias */

/* confirmed: switch(index<15) -> 2-letter asset code, e.g. 14 -> "BB"; jump table at 0x800CFBB8; default "UNKNOWN CAR" */
#define PSX_FN_CarIndexToAssetCode 0x8012ADA0u
#define func_8012ADA0 CarIndexToAssetCode  /* alias */

/* confirmed: switch(index<15) -> display name, e.g. 14 -> "Dark Tooth"; jump table at 0x800CFBF8; default "UNKNOWN CAR" */
#define PSX_FN_CarIndexToName 0x8012AEC4u
#define func_8012AEC4 CarIndexToName  /* alias */

/* guessed: jal at 0x8012CB50 (SingleTrac logo) and 0x8012DDA4 (intro); NOP-ing either skips that movie */
#define PSX_FN_PlayFmv 0x8012B898u
#define func_8012B898 PlayFmv  /* alias */

/* confirmed: decodes a 14-bit password: bits1-3 level-1, bits4-7 char+4, bit9 final-stage, bits10-13 checksum ((char+1)*(level-1))%13; rejects char>=12 via sltiu at 0x8012CED4 */
#define PSX_FN_PasswordDecode 0x8012CE7Cu
#define func_8012CE7C PasswordDecode  /* alias */

/* guessed: password entry UI; draws 'invalid password' at 0x800CFE38 on rejection */
#define PSX_FN_PasswordEntryScreen 0x8012E908u
#define func_8012E908 PasswordEntryScreen  /* alias */

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x8013878Cu
#define func_8013878C BootEntry  /* alias */
